function [EEG] = f_InsertChannel(EEG, chan_name, chan_data, insert_index)
    
    % Insert the new channel into the EEG structure at the specified position
    EEG.chanlocs = [EEG.chanlocs(1:insert_index-1), ...
                    struct('labels', chan_name, ...
                           'theta', 0, ...
                           'radius', 0, ...
                           'X', 0, ...
                           'Y', 0, ...
                           'Z', 0, ...
                           'sph_theta', 0, ...
                           'sph_phi', 0, ...
                           'sph_radius', 0, ...
                           'ref', [], ...
                           'type', [], ...
                           'urchan', []), ...
                    EEG.chanlocs(insert_index:end)];
    EEG.nbchan = EEG.nbchan + 1;
    
    % Extend the EEG data matrix to accommodate the new channel
    EEG.data = [EEG.data(1:insert_index-1, :); ...
                chan_data; ...
                EEG.data(insert_index:end, :)];


end